export const userData = [
  {
    id: 1,
    name: 'Ebiowei Chinedu',
    key: 'ebioweichinedu@gmail.com',
    email: 'ebioweichinedu@gmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: false,
  },
  {
    id: 2,
    name: 'Bankole Oluwaseun',
    key: 'bankoleoluwaseun@gmail.com',
    email: 'bankoleoluwaseun@gmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: false,
  },
  {
    id: 3,
    name: 'Aminu Onohinosen',
    key: 'aminuonohinosen@gmail.com',
    email: 'aminuonohinosen@gmail.com',
    role: 'Viewer',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: false,
  },
  {
    id: 4,
    name: 'Omolara Adeyemo',
    key: 'omolaraadeyemo@gmail.com',
    email: 'omolaraadeyemo@gmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: false,
  },
  {
    id: 5,
    name: 'Rotimi Olumide',
    key: 'Rotimi Olumide',
    email: 'rotimiolumide@gmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: true,
  },
  {
    id: 6,
    name: 'Oluwunmi Shalewa ',
    key: 'Oluwunmi Shalewa ',
    email: 'oluwunmishalewa@gmail.com',
    role: 'Viewer',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: true,
  },
  {
    id: 7,
    name: 'Adaugo Chibike',
    key: 'Adaugo Chibike',
    email: 'adaugochibikegmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: true,
  },
  {
    id: 8,
    name: 'Rotimi Olumide',
    key: 'Rotimi',
    email: 'rotimiolumide@gmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: true,
  },
  {
    id: 9,
    name: 'Oluwunmi Shalewa ',
    key: 'Oluwunmi ',
    email: 'oluwunmishalewa@gmail.com',
    role: 'Viewer',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: true,
  },
  {
    id: 10,
    name: 'Adaugo Chibike',
    key: 'Adaugo',
    email: 'adaugochibikegmail.com',
    role: 'Admin',
    lastActive: 'Nov 11, 2023',
    dateAdded: 'Jan 27, 2023',
    status: true,
  },
]
