export const data = [
  {
    id: 1,
    key: 1,
    name: 'Leopoldo Boutique',
    energyConsumed: 67381,
    energyGenerated: 4495.0,
    location: { street: 'Number 10 ijaoye street', area: 'Jibowu, Lagos' },
    battery: 23.7,
    status: true,
  },
  {
    id: 2,
    key: 2,
    name: 'Alday Banamex',
    energyConsumed: 59934,
    energyGenerated: 7122.0,
    location: {
      street: 'Suite FF11, Noble Complex, Area 10',
      area: 'Garki, Abuja',
    },
    battery: 11.5,
    status: true,
  },
  {
    id: 3,
    key: 3,
    name: 'Dentista Aguilda',
    energyConsumed: 34783,
    energyGenerated: 9824.0,
    location: { street: '3A, Oremeji Street', area: 'Ikeja, Lagos' },
    battery: 94.3,
    status: false,
  },
  {
    id: 4,
    key: 4,
    name: 'Cristela Estilista',
    energyConsumed: 48992,
    energyGenerated: 1734.0,
    location: { street: '153,Egbeda Idimu Road', area: 'Alimosho, Lagos' },
    battery: 62.5,
    status: true,
  },
  {
    id: 5,
    key: 5,
    name: 'Iver Make up',
    energyConsumed: 27867,
    energyGenerated: 1859.0,
    location: { street: 'Number 4 joseph ali street', area: 'Ikoyi, Lagos ' },
    battery: 12.4,
    status: false,
  },
]
