export const data = [
  {
    id: 1,
    key: 1,
    client_name: 'Leopoldo Boutique',
    energy_consumed: 67381,
    energy_generated: 4495.0,
    location: 'Lagos',
    battery: 23.7,
    status: 'OFF',
  },
  {
    id: 2,
    key: 2,
    client_name: 'Alday Banamex',
    energy_consumed: 59934,
    energy_generated: 7122.0,
    location: 'Lagos',
    battery: 11.5,
    status: 'OFF',
  },
  {
    id: 3,
    key: 3,
    client_name: 'Dentista Aguilda',
    energy_consumed: 34783,
    energy_generated: 9824.0,
    location: { street: '3A, Oremeji Street', area: 'Ikeja, Lagos' },
    battery: 94.3,
    status: false,
  },
  {
    id: 4,
    key: 4,
    client_name: 'Cristela Estilista',
    energy_consumed: 48992,
    energy_generated: 1734.0,
    location: 'Lagos',
    battery: 62.5,
    status: 'OFF',
  },
  {
    id: 5,
    key: 5,
    client_name: 'Iver Make up',
    energy_consumed: 27867,
    energy_generated: 1859.0,
    location: 'Lagos',
    battery: 12.4,
    status: 'ON',
  },
]
