export const tableData = [
  {
    id: 1,
    key: 1,
    name: 'January, 2023',
    energyConsumed: 6.35,
    energyGenerated: 14.36,
  },
  {
    id: 2,
    key: 2,
    name: 'December, 2022',
    energyConsumed: 9.52,
    energyGenerated: 21.52,
  },
  {
    id: 3,
    key: 3,
    name: 'November, 2022',
    energyConsumed: 3.18,
    energyGenerated: 7.18,
  },
  {
    id: 4,
    key: 4,
    name: 'October, 2022',
    energyConsumed: 4.67,
    energyGenerated: 9.01,
  },
  {
    id: 5,
    key: 5,
    name: 'September, 2022',
    energyConsumed: 6.82,
    energyGenerated: 14.74,
  },
  {
    id: 6,
    key: 6,
    name: 'August, 2022',
    energyConsumed: 3.18,
    energyGenerated: 7.18,
  },
  {
    id: 7,
    key: 7,
    name: 'July, 2022',
    energyConsumed: 4.67,
    energyGenerated: 9.01,
  },
  {
    id: 8,
    key: 8,
    name: 'June, 2022',
    energyConsumed: 6.82,
    energyGenerated: 14.74,
  },
]

export const adminTableData = [
  {
    id: 1,
    key: 1,
    SHS: 'Farmilii Solar',
    energyConsumed: 6.35,
    energyGenerated: 14.36,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 2,
    key: 2,
    SHS: 'Makanty Rewanda',
    energyConsumed: 9.52,
    energyGenerated: 21.52,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 3,
    key: 3,
    SHS: 'BeMicky washo',
    energyConsumed: 3.18,
    energyGenerated: 7.18,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 4,
    key: 4,
    SHS: 'Demi Wilkinson',
    energyConsumed: 4.67,
    energyGenerated: 9.01,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 5,
    key: 5,
    SHS: 'Candice Wu',
    energyConsumed: 6.82,
    energyGenerated: 14.74,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 6,
    key: 6,
    SHS: 'Quellax Mariot',
    energyConsumed: 3.18,
    energyGenerated: 7.18,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 7,
    key: 7,
    SHS: 'Bluu Sky',
    energyConsumed: 4.67,
    energyGenerated: 9.01,
    capacity: '380 kVA/4.7 kW',
  },
  {
    id: 8,
    key: 8,
    SHS: 'Radonna Volt',
    energyConsumed: 6.82,
    energyGenerated: 14.74,
    capacity: '380 kVA/4.7 kW',
  },
]
